# Generated by Django 4.2.7 on 2023-11-14 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/A', max_length=255)),
                ('breed', models.CharField(default='N/A', max_length=255)),
                ('age', models.PositiveIntegerField(default=1)),
                ('size', models.PositiveIntegerField(choices=[(4, 'unknown'), (1, 'small'), (2, 'medium'), (3, 'large')], default=4)),
                ('gender', models.CharField(choices=[('unknown', 'unknown'), ('female', 'female'), ('male', 'male')], default=4, max_length=255)),
                ('status', models.CharField(choices=[('available', 'available'), ('adopted', 'adopted'), ('pending', 'pending'), ('withdrawn', 'withdrawn')], default='available', max_length=255)),
                ('colour', models.CharField(default='N/A', max_length=255)),
                ('location', models.CharField(default='N/A', max_length=255)),
                ('description', models.TextField(default='N/A')),
                ('behaviour', models.TextField(default='N/A')),
                ('requirements', models.TextField(default='N/A')),
                ('medical_history', models.TextField(default='N/A')),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pet_images')),
                ('pet_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_images', to='pet_listings.petlisting')),
            ],
        ),
    ]
