# Generated by Django 4.2.7 on 2023-11-15 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pet_listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=255)),
                ('all_agree', models.PositiveIntegerField(choices=[(1, 'yes'), (0, 'no')], default=0)),
                ('considerate', models.PositiveIntegerField(choices=[(1, 'yes'), (0, 'no')], default=0)),
                ('medical', models.PositiveIntegerField(choices=[(1, 'yes'), (0, 'no')], default=0)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('age_range', models.CharField(choices=[('18-25', '18-25'), ('25-30', '25-30'), ('30-40', '30-40'), ('40-50', '40-50'), ('50+', '50+')], default='18-25', max_length=10)),
                ('living_arrangement', models.CharField(choices=[('Detached House', 'Detached House'), ('Townhouse', 'Townhouse'), ('Apartment/Condo', 'Apartment/Condo'), ('With outdoor space (fenced)', 'With outdoor space (fenced)'), ('With outdoor space (unfenced)', 'With outdoor space (unfenced)'), ('No outdoor space', 'No outdoor space'), ('I live alone', 'I live alone'), ('I share a space with roommates/family', 'I share a space with roommates/family'), ('I rent my home', 'I rent my home'), ('I own my home', 'I own my home')], default='I live alone', max_length=50)),
                ('have_applied', models.PositiveIntegerField(choices=[(1, 'yes'), (0, 'no')], default=0)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('denied', 'denied'), ('withdrawn', 'withdrawn')], default='pending', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='pet_listings.petlisting')),
                ('pet_seeker', models.ForeignKey(limit_choices_to={'shelter_name__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seeker_applications', to=settings.AUTH_USER_MODEL)),
                ('pet_shelter', models.ForeignKey(limit_choices_to={'shelter_name__isnull': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shelter_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='applications.application')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
