# Generated by Django 4.2.7 on 2023-11-14 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pet_listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=255)),
                ('all_agree', models.PositiveIntegerField(choices=[(1, 'yes'), (0, 'no')], default=0)),
                ('considerate', models.PositiveIntegerField(choices=[(1, 'yes'), (0, 'no')], default=0)),
                ('medical', models.PositiveIntegerField(choices=[(1, 'yes'), (0, 'no')], default=0)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('age_range', models.CharField(choices=[('18-25', '18-25'), ('25-30', '25-30'), ('30-40', '30-40'), ('40-50', '40-50'), ('50+', '50+')], default='18-25', max_length=10)),
                ('living_arrangement', models.CharField(choices=[('Detached House', 'Detached House'), ('Townhouse', 'Townhouse'), ('Apartment/Condo', 'Apartment/Condo'), ('With outdoor space (fenced)', 'With outdoor space (fenced)'), ('With outdoor space (unfenced)', 'With outdoor space (unfenced)'), ('No outdoor space', 'No outdoor space'), ('I live alone', 'I live alone'), ('I share a space with roommates/family', 'I share a space with roommates/family'), ('I rent my home', 'I rent my home'), ('I own my home', 'I own my home')], default='I live alone', max_length=50)),
                ('have_applied', models.PositiveIntegerField(choices=[(1, 'yes'), (0, 'no')], default=0)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('submitted', 'submitted'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='submitted', max_length=255)),
                ('pet_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_listings.petlisting')),
            ],
        ),
    ]
